sudo: false

language: node_js

cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.cache/yarn

node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

  - npm config set spin false

install:
  - yarn

script:
  - yarn run build:prod
  - yarn run build:aot

notifications:
  slack: akveo:q559HckfZMSyZRb803aiLcjH
